### ISSUE TITLE
Update the template repo

### ISSUE THREAD

**Issue by luxas** [racklet/racklet#11]
- [x] Add @Jaakkonen as a maintainer
- [x] Reference the community meeting notes
- [x] Reference the project management board in Github
- [x] Reference the (to be created) CHANGELOG.md in the Racklet repo

**Comment by luxas** [comment]
Done in https://github.com/racklet/render-drawio-action/pull/1 https://github.com/racklet/render-plantuml-action/pull/1 https://github.com/racklet/base-repo-layout/pull/2 https://github.com/racklet/meeting-notes/pull/1

Only this repo left.
