### ISSUE TITLE
Create and document the RFC process

### ISSUE THREAD

**Issue by luxas** [racklet/racklet#17]
Document how we'd like to change Racklet over time using the RFC process.

This includes:
- [x] A README in `docs/rfcs`
- [x] A template RFC `docs/rfcs/0000-rfc-template.md`. Should be a merged variant of the K8s KEP and Rust RFC templates
- [x] Figure out how to publish the RFCs so they are easily browse-able on the Racklet documetation site.

**Comment by luxas** [comment]
This was closed with #18 and #16
